host: <%= ENV['CASSANDRA_HOST'] %>
port: 9042
keyspace: cassandra_testing
username: <%= ENV['CASSANDRA_USERNAME'] %>
password: <%= ENV['CASSANDRA_PASSWORD'] %>
max_retries: 3
retry_delay: 0.5
newrelic: false
password_auth_provider: false
compression: 'lz4'
